# This file was generated by GoReleaser. DO NOT EDIT.
cask "puzzletea" do
  name "puzzletea"
  desc "Terminal-based puzzle game collection built with Bubble Tea"
  homepage "https://github.com/FelineStateMachine/puzzletea"
  version "1.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "puzzletea"

  on_macos do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_amd64.tar.gz"
      sha256 "0fac3434cc92f7b8325d337cdb2b1d83fcd021ba4c42812f950aac937f79af53"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_arm64.tar.gz"
      sha256 "b4f2a61fe9f8be285db61b96a3ebe127ddd151bc64faf4542e1616036d3e2dd0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_amd64.tar.gz"
      sha256 "63dc0b2e2e468be07cf7f22025099c514d186f76f8f6eb9c0e736d8d987f6f03"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_arm64.tar.gz"
      sha256 "310292a061942499acec747b8e34000a46873b756decd435ec64513272d3bbae"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/puzzletea"]
    end
  end

  # No zap stanza required
end
