# This file was generated by GoReleaser. DO NOT EDIT.
cask "puzzletea" do
  name "puzzletea"
  desc "Terminal-based puzzle game collection built with Bubble Tea"
  homepage "https://github.com/FelineStateMachine/puzzletea"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "puzzletea"

  on_macos do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_amd64.tar.gz"
      sha256 "6df896f60a4602a0e8e6efbddae87e4de35f242fcba3ec04729375086fd09206"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_arm64.tar.gz"
      sha256 "b11733e1707219ee9baa58ac9727554d5a9f16543b32c63c8ff497c468d1021a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_amd64.tar.gz"
      sha256 "5e472db722585c350fc783358254308b65fa9701969de1b95384ec9facd33d7c"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_arm64.tar.gz"
      sha256 "67dfaa43695aeb8a0f9111a920bc14ac8bb2371d4eb905156519c5b133873982"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/puzzletea"]
    end
  end

  # No zap stanza required
end
