# This file was generated by GoReleaser. DO NOT EDIT.
cask "puzzletea" do
  name "puzzletea"
  desc "Terminal-based puzzle game collection built with Bubble Tea"
  homepage "https://github.com/FelineStateMachine/puzzletea"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "puzzletea"

  on_macos do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_amd64.tar.gz"
      sha256 "e00b930d222e304623a1e941b59ba929136b6d6fb31bf317698d1f29403810ca"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_darwin_arm64.tar.gz"
      sha256 "0ca9218491de0ef8ff52d51221037b1ff40bf4871484a37132ff738303d32527"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_amd64.tar.gz"
      sha256 "50ac0d7612cccc29825a6e19054dce25563cf5b908e0075b53432856e151251b"
    end
    on_arm do
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v#{version}/puzzletea_#{version}_linux_arm64.tar.gz"
      sha256 "db0e5619ef8d4de6aec173f557483c3f9a6e500428bcdb2c55429fa9bd9a5f9e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/puzzletea"]
    end
  end

  # No zap stanza required
end
