# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puzzletea < Formula
  desc "Terminal-based puzzle game collection built with Bubble Tea"
  homepage "https://github.com/FelineStateMachine/puzzletea"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.2.0/puzzletea_1.2.0_darwin_amd64.tar.gz"
      sha256 "fe6eab8b98d29fcca41bc0580e4f4bc7671ce7a8cd7e331264a9711904795646"

      def install
        bin.install "puzzletea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.2.0/puzzletea_1.2.0_darwin_arm64.tar.gz"
      sha256 "ecf3e6772ef25c6afb9016b74585d50b68d97992df50d4d6a0bfdf2b6c95eca3"

      def install
        bin.install "puzzletea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.2.0/puzzletea_1.2.0_linux_amd64.tar.gz"
      sha256 "5b15eea977f4613ed8b45ee8d8dd9ea7762d0a717f09f9d9ce653b614586329e"
      def install
        bin.install "puzzletea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.2.0/puzzletea_1.2.0_linux_arm64.tar.gz"
      sha256 "60a7291cfd15e108f4cae55ea2e8caef94b729805f916d863678c14da4d6247a"
      def install
        bin.install "puzzletea"
      end
    end
  end

  test do
    system "#{bin}/puzzletea", "--version"
  end
end
