# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puzzletea < Formula
  desc "Terminal-based puzzle game collection built with Bubble Tea"
  homepage "https://github.com/FelineStateMachine/puzzletea"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.1.0/puzzletea_1.1.0_darwin_amd64.tar.gz"
      sha256 "9c4ef87031477533e089e301241e529e5170f92ba423dc54d82e2f3e6c50919b"

      def install
        bin.install "puzzletea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.1.0/puzzletea_1.1.0_darwin_arm64.tar.gz"
      sha256 "80cfc6bc8d08b59d1f5ab977e9c3a2406a509befad3e5bb81af0126121bd9d27"

      def install
        bin.install "puzzletea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.1.0/puzzletea_1.1.0_linux_amd64.tar.gz"
      sha256 "dd3e27b56c4b32416bedc7a0c3f72813b94fca1333bb694c8caf05e036374925"
      def install
        bin.install "puzzletea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FelineStateMachine/puzzletea/releases/download/v1.1.0/puzzletea_1.1.0_linux_arm64.tar.gz"
      sha256 "9a673e6d0fc7f390be90384c479f1643310ef3077e29ae334cb1f17835249961"
      def install
        bin.install "puzzletea"
      end
    end
  end

  test do
    system "#{bin}/puzzletea", "--version"
  end
end
